"""change user table column name to username

Revision ID: c129e31e22e8
Revises: 896567ac9030
Create Date: 2025-12-25 06:02:02.117941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c129e31e22e8'
down_revision: Union[str, Sequence[str], None] = '896567ac9030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "name",
        new_column_name="username"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "username",
        new_column_name="name"
    )
    # ### end Alembic commands ###
